import type { Metadata } from 'next';
import { pretendard, tossface } from '@/styles/fonts';
import '@/styles/global.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ko' className={`${tossface.variable} ${pretendard.variable}`}>
      <body>{children}</body>
    </html>
  );
}
